name: GitHub README STATS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  GITHUB_NAME: pengx17
  GITHUB_EMAIL: pengxiao@outlook.com
  STARRED_NUM: 6
  REPOS_NUM: 6

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: My GitHub Status
        uses: pengx17/github-readme-stats@main
        with:
          STARRED_NUM: ${{ env.STARRED_NUM }}
          REPOS_NUM: ${{ env.REPOS_NUM }}

      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_EMAIL }}"
          git commit -a -m 'docs: push readme.md'
          git push
